// SysDeck bridge — policy (real polkit surface, all live)
// Port of bridge/policy.py semantics: the cockpit edition enforced
// org.sysdeck.* actions through polkit — the actions ship as REAL
// .policy XML (packaging/polkit/*.policy → /usr/share/polkit-1/actions)
// and the operator was prompted via cockpit's superuser channel for
// org.sysdeck.policy.modify. The web edition:
//   - scopes: parsed from the REAL .policy XML files (installed dir
//     first, then the tree) — action ids, descriptions, auth defaults
//   - rules: the operator's rule registry (unseeded workspace)
//   - live: reads the host's REAL /etc/polkit-1/rules.d/*.rules state
//   - sync: materializes the registry into a real polkit rules file
//     (/etc/polkit-1/rules.d/40-sysdeck.rules, privilege-gated)
//   - create/update/delete/toggle on the registry, fully audited
import { db } from '@/lib/db'
import { ok, fail, run, readText } from './shared'
import { readdir, writeFile } from 'fs/promises'

function failE(error: string, source: 'live' | 'hybrid' = 'live') {
  return { ...fail(error), source }
}

async function audit(action: string, detail: string) {
  await db.auditLog.create({ data: { module: 'policy', action, detail } })
}

// ── real .policy XML parsing ─────────────────────────────────────────

const POLICY_DIRS = [
  '/usr/share/polkit-1/actions',
  `${process.cwd()}/../packaging/polkit`,
]

interface ScopeDef {
  scope: string
  description: string
  defaults: string
}

function parsePolicyXml(xml: string): ScopeDef[] {
  const out: ScopeDef[] = []
  const actionRe = /<action id="([^"]+)">([\s\S]*?)<\/action>/g
  let m: RegExpExecArray | null
  while ((m = actionRe.exec(xml)) !== null) {
    const body = m[2]
    const desc =
      body.match(/<description>(?:<!\[CDATA\[)?([\s\S]*?)(?:\]\]>)?<\/description>/)?.[1]?.trim() ?? ''
    const defAllow = body.match(/<allow_(active|inactive)>([^<]+)<\/allow_\1>/g) ?? []
    out.push({
      scope: m[1],
      description: desc || '(no description in policy file)',
      defaults: defAllow.map((d) => d.replace(/<\/?allow_(?:active|inactive)>/g, '')).join(' / ') || 'auth_admin',
    })
  }
  return out
}

async function loadScopes(): Promise<{ scopes: ScopeDef[]; files: string[] }> {
  const scopes = new Map<string, ScopeDef>()
  const files: string[] = []
  for (const dir of POLICY_DIRS) {
    let entries: string[]
    try {
      entries = await readdir(dir)
    } catch {
      continue
    }
    for (const e of entries) {
      if (!e.startsWith('org.sysdeck.') || !e.endsWith('.policy')) continue
      const xml = await readText(`${dir}/${e}`)
      if (!xml) continue
      files.push(e)
      for (const s of parsePolicyXml(xml)) scopes.set(s.scope, s)
    }
  }
  return { scopes: [...scopes.values()].sort((a, b) => a.scope.localeCompare(b.scope)), files }
}

// ── validation helpers ───────────────────────────────────────────────

function validSubject(subject: string): boolean {
  return /^(unix-user|group|netgroup|user):[a-zA-Z0-9._-]+$/.test(subject)
}

// ── real polkit state + sync ─────────────────────────────────────────

const RULES_PATH = '/etc/polkit-1/rules.d/40-sysdeck.rules'

async function liveRules(): Promise<{ files: string[]; sysdeckFile: string | null }> {
  let entries: string[]
  try {
    entries = await readdir('/etc/polkit-1/rules.d')
  } catch {
    return { files: [], sysdeckFile: null }
  }
  const rules = entries.filter((e) => e.endsWith('.rules'))
  let sysdeckFile: string | null = null
  if (rules.includes('40-sysdeck.rules')) {
    sysdeckFile = await readText(RULES_PATH)
  }
  return { files: rules, sysdeckFile }
}

function isRoot(): boolean {
  return typeof process.geteuid === 'function' && process.geteuid() === 0
}

/** Materialize the operator's registry as a REAL polkit .rules file
 *  (polkit's own JS dialect). */
async function syncForReal(): Promise<{ ok: boolean; command: string; error?: string }> {
  const rules = await db.policyRule.findMany({ where: { enabled: true }, orderBy: [{ priority: 'desc' }] })
  const lines = [
    '// /etc/polkit-1/rules.d/40-sysdeck.rules — generated by the sysdeck policy panel',
    '// (org.sysdeck.policy.modify). Regenerate it from the panel after edits.',
    '',
    'polkit.addRule(function(action, subject) {',
    '    if (!action.id.startsWith("org.sysdeck.")) {',
    '        return polkit.Result.NOT_HANDLED;',
    '    }',
  ]
  for (const r of rules) {
    const [kind, name] = r.subject.split(':')
    const subj =
      kind === 'group'
        ? `subject.isInGroup("${name}")`
        : `subject.user === "${name}"`
    lines.push(
      `    // ${r.note ?? r.scope} — priority ${r.priority}`,
      `    if (action.id === "${r.scope}" && ${subj}) {`,
      `        return polkit.Result.${r.effect === 'allow' ? 'YES' : 'NO'};`,
      '    }',
    )
  }
  lines.push('    return polkit.Result.NOT_HANDLED;', '});', '')
  const content = lines.join('\n')
  if (isRoot()) {
    try {
      await writeFile(RULES_PATH, content)
      return { ok: true, command: `write ${RULES_PATH} (${rules.length} rules)` }
    } catch (err) {
      return { ok: false, command: `write ${RULES_PATH}`, error: String(err).split('\n')[0] }
    }
  }
  // sudo -n via tee: the ruleset rides stdin (argv never carries file
  // content), and the write is verified byte-for-byte after it lands.
  const r = await run('sudo', ['-n', 'tee', RULES_PATH], 15_000, { input: content })
  if (r.rc !== 0) {
    return {
      ok: false,
      command: `write ${RULES_PATH}`,
      error: 'org.sysdeck.policy.modify — not authorized: this console process is unprivileged and has no passwordless sudo',
    }
  }
  const landed = await readText(RULES_PATH)
  if (landed !== content) {
    return {
      ok: false,
      command: `write ${RULES_PATH}`,
      error: `verification failed — on-disk ruleset differs from the generated one (${landed.length} vs ${content.length} bytes); regenerate with policy.sync`,
    }
  }
  return { ok: true, command: `sudo -n tee ${RULES_PATH} (${rules.length} rules, verified)` }
}

// ── commands ─────────────────────────────────────────────────────────

export const commands = {
  rules: async () => {
    const rules = await db.policyRule.findMany({ orderBy: [{ priority: 'desc' }, { scope: 'asc' }] })
    const { files } = await liveRules()
    return ok(
      { rules, count: rules.length, rulesDirFiles: files },
      'live',
      rules.length
        ? `operator rule registry (${rules.length} rules) — run policy.sync to materialize them into ${RULES_PATH}`
        : `no rules yet — create one from the scope catalog below; live /etc/polkit-1/rules.d: ${files.length ? files.join(', ') : 'no .rules files on this host'}`,
    )
  },

  scopes: async () => {
    const { scopes, files } = await loadScopes()
    return ok(
      { scopes, count: scopes.length, policyFiles: files },
      'live',
      scopes.length
        ? `real org.sysdeck.* polkit actions parsed from ${files.length} .policy XML files (packaging/polkit → /usr/share/polkit-1/actions)`
        : 'no sysdeck .policy files found (neither installed nor in the tree) — the cockpit edition ships them under packaging/polkit/',
    )
  },

  live: async () => {
    const { files, sysdeckFile } = await liveRules()
    return ok(
      {
        rulesDir: '/etc/polkit-1/rules.d',
        files,
        sysdeckFile,
        polkitd: await run('systemctl', ['is-active', 'polkit'], 5000).then((r) => (r.rc === 0 ? 'active' : 'inactive')),
      },
      'live',
      files.length ? 'real /etc/polkit-1/rules.d listing' : 'no /etc/polkit-1/rules.d on this host (polkit absent or no local rules)',
    )
  },

  sync: async () => {
    const res = await syncForReal()
    await audit('sync', `${res.command} → ${res.ok ? 'written' : 'FAILED'}`)
    if (!res.ok) {
      return failE(res.error ?? 'sync failed', 'hybrid')
    }
    return ok(
      { written: RULES_PATH, command: res.command },
      'live',
      'the registry is now the live polkit rules file — reload polkit (systemctl reload polkit) applies it',
    )
  },

  create: async (args: Record<string, unknown>) => {
    const scope = String(args.scope ?? '').trim()
    const subject = String(args.subject ?? '').trim()
    const effect = String(args.effect ?? 'allow').trim().toLowerCase()
    const priority = Number.isInteger(args.priority) ? Number(args.priority) : 50
    const note = args.note ? String(args.note).trim() : null
    if (!scope) return failE('scope is required (e.g. org.sysdeck.builder.modify)')
    const { scopes } = await loadScopes()
    if (!scopes.some((s) => s.scope === scope)) return failE(`unknown scope '${scope}' — call policy.scopes for the real action catalog (${scopes.length} actions)`)
    if (!subject) return failE('subject is required (unix-user:<name> or group:<name>)')
    if (!validSubject(subject)) return failE(`invalid subject '${subject}' — expected unix-user:<name> or group:<name>`)
    if (!['allow', 'deny'].includes(effect)) return failE('effect must be allow or deny')
    if (priority < 0 || priority > 100) return failE('priority must be 0-100')
    const row = await db.policyRule.create({ data: { scope, subject, effect, priority, note } })
    await audit('policy.create', `${effect} ${scope} for ${subject} (priority ${priority})`)
    return ok({ rule: row }, 'live')
  },

  update: async (args: Record<string, unknown>) => {
    const id = String(args.id ?? '').trim()
    if (!id) return failE('id is required')
    const rule = await db.policyRule.findUnique({ where: { id } })
    if (!rule) return failE('rule not found')
    const data: { effect?: string; priority?: number; subject?: string; note?: string | null; enabled?: boolean } = {}
    if (args.effect !== undefined) {
      const effect = String(args.effect).trim().toLowerCase()
      if (!['allow', 'deny'].includes(effect)) return failE('effect must be allow or deny')
      data.effect = effect
    }
    if (args.priority !== undefined) {
      const priority = Number(args.priority)
      if (!Number.isInteger(priority) || priority < 0 || priority > 100) return failE('priority must be an integer 0-100')
      data.priority = priority
    }
    if (args.subject !== undefined) {
      const subject = String(args.subject).trim()
      if (!validSubject(subject)) return failE(`invalid subject '${subject}' — expected unix-user:<name> or group:<name>`)
      data.subject = subject
    }
    if (args.note !== undefined) data.note = args.note === null ? null : String(args.note).trim()
    if (Object.keys(data).length === 0) return failE('nothing to update — pass effect, priority, subject and/or note')
    const row = await db.policyRule.update({ where: { id }, data })
    await audit('policy.update', `rule ${rule.scope} ${rule.subject}: ${Object.entries(data).map(([k, v]) => `${k}=${v}`).join(', ')}`)
    return ok({ rule: row }, 'live')
  },

  delete: async (args: Record<string, unknown>) => {
    const id = String(args.id ?? '').trim()
    if (!id) return failE('id is required')
    const rule = await db.policyRule.findUnique({ where: { id } })
    if (!rule) return failE('rule not found')
    await db.policyRule.delete({ where: { id } })
    await audit('policy.delete', `removed ${rule.effect} ${rule.scope} for ${rule.subject}`)
    return ok({ deleted: { id, scope: rule.scope, subject: rule.subject } }, 'live')
  },

  toggle: async (args: Record<string, unknown>) => {
    const id = String(args.id ?? '').trim()
    if (!id) return failE('id is required')
    const rule = await db.policyRule.findUnique({ where: { id } })
    if (!rule) return failE('rule not found')
    const row = await db.policyRule.update({ where: { id }, data: { enabled: !rule.enabled } })
    await audit('policy.toggle', `${rule.scope} ${rule.subject} → ${row.enabled ? 'enabled' : 'disabled'}`)
    return ok({ rule: row, enabled: row.enabled }, 'live')
  },

  audit: async () => {
    const rows = await db.auditLog.findMany({
      where: { OR: [{ module: 'policy' }, { action: { contains: 'policy' } }] },
      orderBy: { ts: 'desc' },
      take: 50,
    })
    return ok({ entries: rows, count: rows.length }, 'live', 'AuditLog rows filtered module=policy OR action contains "policy"')
  },
}
